//
// File generated by HDevelop for HALCON/.NET (C#) Version 25.11.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // External procedures 
  // Chapter: Develop
  // Short Description: Switch dev_update_pc, dev_update_var, and dev_update_window to 'on'. 
  public void dev_update_on ()
  {

    // Initialize local and output iconic variables 
    //This procedure sets different update settings to 'on'.
    //
    // dev_update_pc(...); only in hdevelop
    // dev_update_var(...); only in hdevelop
    // dev_update_window(...); only in hdevelop


    return;
  }

  // Chapter: Graphics / Text
  // Short Description: Write one or multiple text messages. 
  public void disp_message (HTuple hv_WindowHandle, HTuple hv_String, HTuple hv_CoordSystem, 
      HTuple hv_Row, HTuple hv_Column, HTuple hv_Color, HTuple hv_Box)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_GenParamName = new HTuple(), hv_GenParamValue = new HTuple();
    HTuple   hv_Color_COPY_INP_TMP = new HTuple(hv_Color);
    HTuple   hv_Column_COPY_INP_TMP = new HTuple(hv_Column);
    HTuple   hv_CoordSystem_COPY_INP_TMP = new HTuple(hv_CoordSystem);
    HTuple   hv_Row_COPY_INP_TMP = new HTuple(hv_Row);

    // Initialize local and output iconic variables 
    try
    {
      //This procedure displays text in a graphics window.
      //
      //Input parameters:
      //WindowHandle: The WindowHandle of the graphics window, where
      //   the message should be displayed.
      //String: A tuple of strings containing the text messages to be displayed.
      //CoordSystem: If set to 'window', the text position is given
      //   with respect to the window coordinate system.
      //   If set to 'image', image coordinates are used.
      //   (This may be useful in zoomed images.)
      //Row: The row coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Column: The column coordinate of the desired text position.
      //   You can pass a single value or a tuple of values.
      //   See the explanation below.
      //   Default: 12.
      //Color: defines the color of the text as string.
      //   If set to [] or '' the currently set color is used.
      //   If a tuple of strings is passed, the colors are used cyclically
      //   for every text position defined by Row and Column,
      //   or every new text line in case of |Row| == |Column| == 1.
      //Box: A tuple controlling a possible box surrounding the text.
      //   Its entries:
      //   - Box[0]: Controls the box and its color. Possible values:
      //     -- 'true' (Default): An orange box is displayed.
      //     -- 'false': No box is displayed.
      //     -- color string: A box is displayed in the given color, e.g., 'white', '#FF00CC'.
      //   - Box[1] (Optional): Controls the shadow of the box. Possible values:
      //     -- 'true' (Default): A shadow is displayed in
      //               darker orange if Box[0] is not a color and in 'white' otherwise.
      //     -- 'false': No shadow is displayed.
      //     -- color string: A shadow is displayed in the given color, e.g., 'white', '#FF00CC'.
      //
      //It is possible to display multiple text strings in a single call.
      //In this case, some restrictions apply on the
      //parameters String, Row, and Column:
      //They can only have either 1 entry or n entries.
      //Behavior in the different cases:
      //   - Multiple text positions are specified, i.e.,
      //       - |Row| == n, |Column| == n
      //       - |Row| == n, |Column| == 1
      //       - |Row| == 1, |Column| == n
      //     In this case we distinguish:
      //       - |String| == n: Each element of String is displayed
      //                        at the corresponding position.
      //       - |String| == 1: String is displayed n times
      //                        at the corresponding positions.
      //   - Exactly one text position is specified,
      //      i.e., |Row| == |Column| == 1:
      //      Each element of String is display in a new textline.
      //
      //
      //Convert the parameters for disp_text.
      if ((int)((new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(new HTuple()))).TupleOr(
          new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(new HTuple())))) != 0)
      {

        hv_Color_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP.Dispose();
        hv_GenParamName.Dispose();
        hv_GenParamValue.Dispose();

        return;
      }
      if ((int)(new HTuple(hv_Row_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Row_COPY_INP_TMP.Dispose();
        hv_Row_COPY_INP_TMP = 12;
      }
      if ((int)(new HTuple(hv_Column_COPY_INP_TMP.TupleEqual(-1))) != 0)
      {
        hv_Column_COPY_INP_TMP.Dispose();
        hv_Column_COPY_INP_TMP = 12;
      }
      //
      //Convert the parameter Box to generic parameters.
      hv_GenParamName.Dispose();
      hv_GenParamName = new HTuple();
      hv_GenParamValue.Dispose();
      hv_GenParamValue = new HTuple();
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(0))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleEqual("false"))) != 0)
        {
          //Display no box
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(0))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "box_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(0));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      if ((int)(new HTuple((new HTuple(hv_Box.TupleLength())).TupleGreater(1))) != 0)
      {
        if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleEqual("false"))) != 0)
        {
          //Display no shadow.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              "false");
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
        else if ((int)(new HTuple(((hv_Box.TupleSelect(1))).TupleNotEqual(
            "true"))) != 0)
        {
          //Set a shadow color other than the default.
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamName = hv_GenParamName.TupleConcat(
              "shadow_color");
          hv_GenParamName.Dispose();
          hv_GenParamName = ExpTmpLocalVar_GenParamName;
          }
          }
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          {
          HTuple 
            ExpTmpLocalVar_GenParamValue = hv_GenParamValue.TupleConcat(
              hv_Box.TupleSelect(1));
          hv_GenParamValue.Dispose();
          hv_GenParamValue = ExpTmpLocalVar_GenParamValue;
          }
          }
        }
      }
      //Restore default CoordSystem behavior.
      if ((int)(new HTuple(hv_CoordSystem_COPY_INP_TMP.TupleNotEqual("window"))) != 0)
      {
        hv_CoordSystem_COPY_INP_TMP.Dispose();
        hv_CoordSystem_COPY_INP_TMP = "image";
      }
      //
      if ((int)(new HTuple(hv_Color_COPY_INP_TMP.TupleEqual(""))) != 0)
      {
        //disp_text does not accept an empty string for Color.
        hv_Color_COPY_INP_TMP.Dispose();
        hv_Color_COPY_INP_TMP = new HTuple();
      }
      //
      HOperatorSet.DispText(hv_WindowHandle, hv_String, hv_CoordSystem_COPY_INP_TMP, 
          hv_Row_COPY_INP_TMP, hv_Column_COPY_INP_TMP, hv_Color_COPY_INP_TMP, hv_GenParamName, 
          hv_GenParamValue);

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      return;
    }
    catch (HalconException HDevExpDefaultException)
    {

      hv_Color_COPY_INP_TMP.Dispose();
      hv_Column_COPY_INP_TMP.Dispose();
      hv_CoordSystem_COPY_INP_TMP.Dispose();
      hv_Row_COPY_INP_TMP.Dispose();
      hv_GenParamName.Dispose();
      hv_GenParamValue.Dispose();

      throw HDevExpDefaultException;
    }
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_Map, ho_GrayImage, ho_Mark1Rect=null;
    HObject ho_ImageReducedMark1=null, ho_Mark2Rect=null, ho_ImageReducedMark2=null;
    HObject ho_Image1=null;

    // Local control variables 

    HTuple hv_AcqHandle = new HTuple(), hv_Width = new HTuple();
    HTuple hv_Height = new HTuple(), hv_WindowHandle = new HTuple();
    HTuple hv_CameraParameters = new HTuple(), hv_CameraPose = new HTuple();
    HTuple hv_row = new HTuple(), hv_column = new HTuple();
    HTuple hv_rowworld = new HTuple(), hv_colmunworld = new HTuple();
    HTuple hv_HomMat2D = new HTuple(), hv_ErrorSum = new HTuple();
    HTuple hv_i = new HTuple(), hv_CalcX = new HTuple(), hv_CalcY = new HTuple();
    HTuple hv_DiffX = new HTuple(), hv_DiffY = new HTuple();
    HTuple hv_Error = new HTuple(), hv_AverageError = new HTuple();
    HTuple hv__ = new HTuple(), hv_Button = new HTuple(), hv_load_from_file = new HTuple();
    HTuple hv_ModelID1 = new HTuple(), hv_ModelID2 = new HTuple();
    HTuple hv_Params = new HTuple(), hv_RefMark1Row = new HTuple();
    HTuple hv_RefMark1Col = new HTuple(), hv_RefMark2Row = new HTuple();
    HTuple hv_RefMark2Col = new HTuple(), hv_StdMark1X = new HTuple();
    HTuple hv_StdMark1Y = new HTuple(), hv_StdMark2X = new HTuple();
    HTuple hv_StdMark2Y = new HTuple(), hv_StdCenterX = new HTuple();
    HTuple hv_StdCenterY = new HTuple(), hv_StdAngle = new HTuple();
    HTuple hv_Exception = new HTuple(), hv_Row11 = new HTuple();
    HTuple hv_Column11 = new HTuple(), hv_Row12 = new HTuple();
    HTuple hv_Column12 = new HTuple(), hv_Row21 = new HTuple();
    HTuple hv_Column21 = new HTuple(), hv_Row22 = new HTuple();
    HTuple hv_Column22 = new HTuple(), hv_Mark1Row = new HTuple();
    HTuple hv_Mark1Col = new HTuple(), hv_Mark1Angle = new HTuple();
    HTuple hv_Score1 = new HTuple(), hv_Mark2Row = new HTuple();
    HTuple hv_Mark2Col = new HTuple(), hv_Mark2Angle = new HTuple();
    HTuple hv_Score2 = new HTuple(), hv_CurMark1X = new HTuple();
    HTuple hv_CurMark1Y = new HTuple(), hv_CurMark2X = new HTuple();
    HTuple hv_CurMark2Y = new HTuple(), hv_CurCenterX = new HTuple();
    HTuple hv_CurCenterY = new HTuple(), hv_CurAngle = new HTuple();
    HTuple hv_DeltaX = new HTuple(), hv_DeltaY = new HTuple();
    HTuple hv_DeltaAngle = new HTuple(), hv___Tmp_Ctrl_0_1 = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_Map);
    HOperatorSet.GenEmptyObj(out ho_GrayImage);
    HOperatorSet.GenEmptyObj(out ho_Mark1Rect);
    HOperatorSet.GenEmptyObj(out ho_ImageReducedMark1);
    HOperatorSet.GenEmptyObj(out ho_Mark2Rect);
    HOperatorSet.GenEmptyObj(out ho_ImageReducedMark2);
    HOperatorSet.GenEmptyObj(out ho_Image1);
    try
    {
      //====================== ����������ʼ��ģ�� ======================
      //��GigE Vision2Э��Ĺ�ҵ�������ȡ������AcqHandle
      //����˵����������͡��ӿ�������ͼ�����/�߶�(0=�Զ�)����ʼ��/�С����ظ�ʽ������ɨ�衢�˿ڡ�������к�
      hv_AcqHandle.Dispose();
      HOperatorSet.OpenFramegrabber("GigEVision2", 0, 0, 0, 0, 0, 0, "progressive", 
          -1, "default", -1, "false", "default", "c42f90f6ad7a_GEV_MVCA06010GC", 
          0, -1, out hv_AcqHandle);
      //��������첽�ɼ�ģʽ��-1��ʾ���޵ȴ����ɼ��ٶȱ�ͬ��ģʽ���Ҳ���������
      HOperatorSet.GrabImageStart(hv_AcqHandle, -1);
      //�ر�����Զ��ع⹦�ܣ���ҵ�Ӿ�����رգ�����ͼ�����Ȳ��ȶ����¼�����
      HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "ExposureAuto", "Off");
      //�ر�����Զ����湦�ܣ�ԭ��ͬ�ϣ���֤ͼ��Ҷ�ֵ�㶨
      HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "GainAuto", "Off");
      //��������̶��ع�ʱ��Ϊ5000΢��(��5����)�������ֳ����յ���
      HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "ExposureTime", 5000);
      //��������̶�����Ϊ1������Խ��ͼ��Խ��������Խ��
      HOperatorSet.SetFramegrabberParam(hv_AcqHandle, "Gain", 1);
      //�첽ץȡ��һ��ͼ�����ں������ڴ����ͱ궨
      ho_Image.Dispose();
      HOperatorSet.GrabImageAsync(out ho_Image, hv_AcqHandle, -1);
      //��ȡ��ǰͼ��Ŀ��Ⱥ͸߶ȣ�������3072x2048(600������)
      hv_Width.Dispose();hv_Height.Dispose();
      HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);
      //��һ��800x600�ĺ�ɫ��ʾ���ڣ���ȡ���ھ��WindowHandle
      HOperatorSet.SetWindowAttr("background_color","black");
      HOperatorSet.OpenWindow(0,0,800,600,0,"visible","",out hv_WindowHandle);
      HDevWindowStack.Push(hv_WindowHandle);
      //���������Զ����£�ȷ��ͼ���������ʵʱ��ʾ
      dev_update_on();
      //����ڲξ�����Halcon�궨�������ɣ����������ѧ���ԣ��̶�����
      //��ʽ��[���ģ��, ����, ����ϵ��, ��Ԫ����, ��Ԫ�߶�, ������, ������, ͼ���, ͼ���]
      hv_CameraParameters.Dispose();
      hv_CameraParameters = new HTuple();
      hv_CameraParameters[0] = "area_scan_hypercentric_division";
      hv_CameraParameters[1] = 0.000124491;
      hv_CameraParameters[2] = -150.474;
      hv_CameraParameters[3] = 2.42129e-06;
      hv_CameraParameters[4] = 2.4e-06;
      hv_CameraParameters[5] = 2661.56;
      hv_CameraParameters[6] = 433.2;
      hv_CameraParameters[7] = 3072;
      hv_CameraParameters[8] = 2048;
      //�����Σ������������ڻ�еƽ̨��λ����̬���������þŵ����궨���˲�����δʹ��
      hv_CameraPose.Dispose();
      hv_CameraPose = new HTuple();
      hv_CameraPose[0] = -0.00924934;
      hv_CameraPose[1] = 0.0054012;
      hv_CameraPose[2] = 0.00150158;
      hv_CameraPose[3] = 359.993;
      hv_CameraPose[4] = 0.0281918;
      hv_CameraPose[5] = 359.63;
      hv_CameraPose[6] = 0;
      //9���궨������������꣬�ֶ��ɼ��궨����9��Բ���������λ��
      hv_row.Dispose();
      hv_row = new HTuple();
      hv_row[0] = 123.779;
      hv_row[1] = 123.717;
      hv_row[2] = 123.775;
      hv_row[3] = 322.0;
      hv_row[4] = 322.0;
      hv_row[5] = 322.0;
      hv_row[6] = 520.212;
      hv_row[7] = 520.274;
      hv_row[8] = 520.215;
      //9���궨������������꣬��Ӧ����9�������λ��
      hv_column.Dispose();
      hv_column = new HTuple();
      hv_column[0] = 213.203;
      hv_column[1] = 411.495;
      hv_column[2] = 609.788;
      hv_column[3] = 213.2;
      hv_column[4] = 411.5;
      hv_column[5] = 609.782;
      hv_column[6] = 213.207;
      hv_column[7] = 411.5;
      hv_column[8] = 609.785;
      //9���궨���Ӧ�Ļ�еƽ̨Y����������(��λ��mm)���ֶ��ƶ�ƽ̨��¼
      hv_rowworld.Dispose();
      hv_rowworld = new HTuple();
      hv_rowworld[0] = 200.203;
      hv_rowworld[1] = 200.495;
      hv_rowworld[2] = 200.788;
      hv_rowworld[3] = 413.2;
      hv_rowworld[4] = 411.5;
      hv_rowworld[5] = 409.782;
      hv_rowworld[6] = 613.207;
      hv_rowworld[7] = 611.5;
      hv_rowworld[8] = 609.785;
      //9���궨���Ӧ�Ļ�еƽ̨X����������(��λ��mm)����Ӧ����9�����Xλ��
      hv_colmunworld.Dispose();
      hv_colmunworld = new HTuple();
      hv_colmunworld[0] = 123.779;
      hv_colmunworld[1] = 323.717;
      hv_colmunworld[2] = 523.775;
      hv_colmunworld[3] = 322.0;
      hv_colmunworld[4] = 622.0;
      hv_colmunworld[5] = 822.0;
      hv_colmunworld[6] = 620.212;
      hv_colmunworld[7] = 820.274;
      hv_colmunworld[8] = 1020.215;
      //�������ӣ�����2D��η���任����HomMat2D
      hv_HomMat2D.Dispose();
      HOperatorSet.VectorToHomMat2d(hv_column, hv_row, hv_colmunworld, hv_rowworld, 
          out hv_HomMat2D);
      //====================== �궨�����֤ ======================
      //��ʼ������ۼӺ�Ϊ0.0�����ڴ洢���е������ܺ�
      hv_ErrorSum.Dispose();
      hv_ErrorSum = 0.0;
      //ѭ������9���궨�㣬i��0��8������1
      for (hv_i=0; (int)hv_i<=8; hv_i = (int)hv_i + 1)
      {
        //�ñ궨���󽫵�i�������������ת��Ϊ����õ�����������
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_CalcX.Dispose();hv_CalcY.Dispose();
        HOperatorSet.AffineTransPoint2d(hv_HomMat2D, hv_column.TupleSelect(hv_i), 
            hv_row.TupleSelect(hv_i), out hv_CalcX, out hv_CalcY);
        }
        //����X�᷽���������ֵ - ��ʵ����ֵ
        hv_DiffX.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_DiffX = hv_CalcX-(hv_colmunworld.TupleSelect(
            hv_i));
        }
        //����Y�᷽���������ֵ - ��ʵ����ֵ
        hv_DiffY.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_DiffY = hv_CalcY-(hv_rowworld.TupleSelect(
            hv_i));
        }
        //����õ��ŷ�Ͼ������(�������ֱ�߾���)
        //��ʽ��Error = ��(DiffX2 + DiffY2)����ӳ�õ��ʵ�ʶ�λ���
        hv_Error.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_Error = (((hv_DiffX*hv_DiffX)+(hv_DiffY*hv_DiffY))).TupleSqrt()
            ;
        }
        //����ǰ�������ۼӵ��������
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_ErrorSum = hv_ErrorSum+hv_Error;
        hv_ErrorSum.Dispose();
        hv_ErrorSum = ExpTmpLocalVar_ErrorSum;
        }
        }
      }
      //����9�����ƽ������ӳ�����궨�����徫��
      hv_AverageError.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_AverageError = hv_ErrorSum/9.0;
      }
      //$'.4f'��ʾ����������ʽ��Ϊ����4λС�����ַ���
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      disp_message(hv_WindowHandle, ("�궨��ɣ�ƽ�����: "+(hv_AverageError.TupleString(
          ".4f")))+" mm", "window", 12, 12, "green", "true");
      }
      //���궨���󱣴浽�����ļ����´����п�ֱ�Ӽ��أ��������±궨
      HOperatorSet.WriteTuple(hv_HomMat2D, "H:/Halcon/hom_mat2d_9point.tup");
      //���ɾ������У��ӳ�����ʹ��˫���Բ�ֵ�㷨
      //���ã���ǰ�����ÿ�����ص�У��λ�ã�ʵʱ���ʱ�ٶȸ���
      ho_Map.Dispose();
      HOperatorSet.GenRadialDistortionMap(out ho_Map, hv_CameraParameters, hv_CameraParameters, 
          "bilinear");
      //����ɫͼ��ת��Ϊ�Ҷ�ͼ����״ģ��ƥ��ֻ���ڻҶ�ͼ�Ͻ���
      ho_GrayImage.Dispose();
      HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
      //��ȡ��ǰ����ڵľ�������ں�����ͼ����
      if (HDevWindowStack.IsOpen())
      {
        hv_WindowHandle = HDevWindowStack.GetActive();
      }
      //���û�ͼ��ɫΪ��ɫ
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetColor(HDevWindowStack.GetActive(), "green");
      }
      //���û�ͼģʽΪ��Եģʽ��ֻ����ͼ�����������
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetDraw(HDevWindowStack.GetActive(), "margin");
      }
      //���û�ͼ��������Ϊ2����
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.SetLineWidth(HDevWindowStack.GetActive(), 2);
      }
      //====================== ģ��ѡ��ģʽģ�� ======================
      //��ʾ��ǰ�Ҷ�ͼ����Ϊ����
      if (HDevWindowStack.IsOpen())
      {
        HOperatorSet.DispObj(ho_GrayImage, HDevWindowStack.GetActive());
      }
      //�ڴ������Ͻ���ʾ������ʾ��Ϣ
      disp_message(hv_WindowHandle, "�������������ģ��    �Ҽ����½�ģ��", "window", 
          12, 12, "black", "true");
      //�ȴ��û�����������ص�����С��кͰ�ť���(1=���,2=�м�,3=�Ҽ�)
      hv__.Dispose();hv___Tmp_Ctrl_0_1.Dispose();hv_Button.Dispose();
      HOperatorSet.GetMbutton(hv_WindowHandle, out hv__, out hv___Tmp_Ctrl_0_1, out hv_Button);
      //�ж��û��Ƿ�����������
      if ((int)(new HTuple(hv_Button.TupleEqual(1))) != 0)
      {
        //���ü���ģ���־Ϊtrue
        hv_load_from_file.Dispose();
        hv_load_from_file = 1;
        //��ʾ��ѡ�����ģ�����ʾ��Ϣ
        disp_message(hv_WindowHandle, "��ѡ�񣺼���ģ��", "window", 32, 12, "green", 
            "true");
        //�쳣����飬��ֹģ���ļ������ڵ��³������
        try
        {
          //��ȡMark�����״ģ���ļ�����ȡģ��ID
          hv_ModelID1.Dispose();
          HOperatorSet.ReadShapeModel("MarkModel1.shm", out hv_ModelID1);
          hv_ModelID2.Dispose();
          HOperatorSet.ReadShapeModel("MarkModel2.shm", out hv_ModelID2);
          //��ȡ�����ģ��ο��������
          hv_Params.Dispose();
          HOperatorSet.ReadTuple("MarkParams.tup", out hv_Params);
          //�Ӳ��������н�����һ��Mark��Ĳο�������
          hv_RefMark1Row.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_RefMark1Row = hv_Params.TupleSelect(
              0);
          }
          hv_RefMark1Col.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_RefMark1Col = hv_Params.TupleSelect(
              1);
          }
          //�Ӳ��������н����ڶ���Mark��Ĳο�������
          hv_RefMark2Row.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_RefMark2Row = hv_Params.TupleSelect(
              2);
          }
          hv_RefMark2Col.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_RefMark2Col = hv_Params.TupleSelect(
              3);
          }
          //��ʾģ����سɹ�����ʾ��Ϣ
          disp_message(hv_WindowHandle, "ģ����سɹ�", "window", 52, 12, "green", 
              "true");
          //����һ��Mark��Ĳο���������ת��Ϊ��׼��������
          hv_StdMark1X.Dispose();hv_StdMark1Y.Dispose();
          HOperatorSet.AffineTransPoint2d(hv_HomMat2D, hv_RefMark1Col, hv_RefMark1Row, 
              out hv_StdMark1X, out hv_StdMark1Y);
          //���ڶ���Mark��Ĳο���������ת��Ϊ��׼��������
          hv_StdMark2X.Dispose();hv_StdMark2Y.Dispose();
          HOperatorSet.AffineTransPoint2d(hv_HomMat2D, hv_RefMark2Col, hv_RefMark2Row, 
              out hv_StdMark2X, out hv_StdMark2Y);
          //�����׼���ĵ�X���꣺����Mark��X�����ƽ��ֵ
          hv_StdCenterX.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_StdCenterX = (hv_StdMark1X+hv_StdMark2X)/2.0;
          }
          //�����׼���ĵ�Y���꣺����Mark��Y�����ƽ��ֵ
          hv_StdCenterY.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_StdCenterY = (hv_StdMark1Y+hv_StdMark2Y)/2.0;
          }
          //�����׼�Ƕȣ�����Mark��������X��������ļн�
          //��ʽ��atan2(��Y, ��X)������ֵΪ���ȣ���Χ[-��, ��]
          hv_StdAngle.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_StdAngle = ((hv_StdMark2Y-hv_StdMark1Y)).TupleAtan2(
              hv_StdMark2X-hv_StdMark1X);
          }
        }
        // catch (Exception) 
        catch (HalconException HDevExpDefaultException1)
        {
          HDevExpDefaultException1.ToHTuple(out hv_Exception);
          disp_message(hv_WindowHandle, "ģ�����ʧ�ܣ������ļ��Ƿ����", "window", 
              52, 12, "red", "true");
        }

      }
      else
      {
        //���ü���ģ���־Ϊfalse
        hv_load_from_file.Dispose();
        hv_load_from_file = 0;
        //��ʾ��ѡ���½�ģ�����ʾ��Ϣ
        disp_message(hv_WindowHandle, "��ѡ���½�ģ��", "window", 32, 12, "green", 
            "true");
        //====================== �½���һ��Mark��ģ�� ======================
        //��ʾ�û���ѡ��һ��Mark������
        disp_message(hv_WindowHandle, "���ѡ��һ��Mark�����򣨾��Σ�", "window", 
            12, 12, "black", "true");
        //�����û��ڴ����ϻ���һ�����Σ����ؾ��ε����ϽǺ����½�����
        hv_Row11.Dispose();hv_Column11.Dispose();hv_Row12.Dispose();hv_Column12.Dispose();
        HOperatorSet.DrawRectangle1(hv_WindowHandle, out hv_Row11, out hv_Column11, 
            out hv_Row12, out hv_Column12);
        //���ݻ��Ƶ���������һ����������
        ho_Mark1Rect.Dispose();
        HOperatorSet.GenRectangle1(out ho_Mark1Rect, hv_Row11, hv_Column11, hv_Row12, 
            hv_Column12);
        //��ԭ�Ҷ�ͼ�вü������������ڵ�ͼ�����ڴ���ģ��
        ho_ImageReducedMark1.Dispose();
        HOperatorSet.ReduceDomain(ho_GrayImage, ho_Mark1Rect, out ho_ImageReducedMark1
            );
        //������״ģ�壬������ת������(0-360��)
        //����������ͼ�񡢽�������������ʼ�Ƕȡ��Ƕȷ�Χ���ǶȲ������Ż���ʽ�����ԡ��Աȶȡ���С�Աȶȡ�ģ��ID
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_ModelID1.Dispose();
        HOperatorSet.CreateShapeModel(ho_ImageReducedMark1, "auto", (new HTuple(0)).TupleRad()
            , (new HTuple(360)).TupleRad(), "auto", "auto", "use_polarity", "auto", 
            "auto", out hv_ModelID1);
        }
        //�������������������꣬��Ϊ��һ��Mark��Ĳο�����
        hv__.Dispose();hv_RefMark1Row.Dispose();hv_RefMark1Col.Dispose();
        HOperatorSet.AreaCenter(ho_Mark1Rect, out hv__, out hv_RefMark1Row, out hv_RefMark1Col);

        //====================== �½��ڶ���Mark��ģ�� ======================
        //��ʾ�û���ѡ�ڶ���Mark������
        disp_message(hv_WindowHandle, "���ѡ�ڶ���Mark�����򣨾��Σ�", "window", 
            32, 12, "black", "true");
        //�����û��ڴ����ϻ��Ƶڶ�������
        hv_Row21.Dispose();hv_Column21.Dispose();hv_Row22.Dispose();hv_Column22.Dispose();
        HOperatorSet.DrawRectangle1(hv_WindowHandle, out hv_Row21, out hv_Column21, 
            out hv_Row22, out hv_Column22);
        //���ɵڶ�����������
        ho_Mark2Rect.Dispose();
        HOperatorSet.GenRectangle1(out ho_Mark2Rect, hv_Row21, hv_Column21, hv_Row22, 
            hv_Column22);
        //�ü����ڶ���Mark�������ͼ��
        ho_ImageReducedMark2.Dispose();
        HOperatorSet.ReduceDomain(ho_GrayImage, ho_Mark2Rect, out ho_ImageReducedMark2
            );
        //�����ڶ���Mark�����״ģ��
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_ModelID2.Dispose();
        HOperatorSet.CreateShapeModel(ho_ImageReducedMark2, "auto", (new HTuple(0)).TupleRad()
            , (new HTuple(360)).TupleRad(), "auto", "auto", "use_polarity", "auto", 
            "auto", out hv_ModelID2);
        }
        //����ڶ��������������������
        hv__.Dispose();hv_RefMark2Row.Dispose();hv_RefMark2Col.Dispose();
        HOperatorSet.AreaCenter(ho_Mark2Rect, out hv__, out hv_RefMark2Row, out hv_RefMark2Col);

        //��ʾ�û��Ƿ񱣴浱ǰģ��
        disp_message(hv_WindowHandle, "�Ƿ񱣴浱ǰģ�壿  (���=�ǣ��Ҽ�=��)", "window", 
            92, 12, "black", "true");
        //�ȴ��û������ȷ��
        hv__.Dispose();hv___Tmp_Ctrl_0_1.Dispose();hv_Button.Dispose();
        HOperatorSet.GetMbutton(hv_WindowHandle, out hv__, out hv___Tmp_Ctrl_0_1, 
            out hv_Button);
        //����û�������������ģ��
        if ((int)(new HTuple(hv_Button.TupleEqual(1))) != 0)
        {
          //�����һ��Mark�����״ģ�嵽�ļ�
          HOperatorSet.WriteShapeModel(hv_ModelID1, "MarkModel1.shm");
          //����ڶ���Mark�����״ģ�嵽�ļ�
          HOperatorSet.WriteShapeModel(hv_ModelID2, "MarkModel2.shm");
          //������Mark��Ĳο�������������
          hv_Params.Dispose();
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          hv_Params = new HTuple();
          hv_Params = hv_Params.TupleConcat(hv_RefMark1Row, hv_RefMark1Col, hv_RefMark2Row, hv_RefMark2Col);
          }
          //����ο�����������ļ�
          HOperatorSet.WriteTuple(hv_Params, "MarkParams.tup");
          //��ʾģ���ѱ������ʾ��Ϣ
          disp_message(hv_WindowHandle, "ģ���ѱ��棬���������г���ѡ�񡰼���ģ�塱", 
              "window", 132, 12, "black", "true");
          //ֹͣ�������û��������н������ģʽ
          // stop(...); only in hdevelop
        }
      }
      //====================== ʵʱ������ƫ��ѭ�� ======================
      //����ѭ������������ͼ��ɼ��ͼ��
      while ((int)(1) != 0)
      {
        //�첽ץȡʵʱͼ��
        ho_Image1.Dispose();
        HOperatorSet.GrabImageAsync(out ho_Image1, hv_AcqHandle, -1);
        //ʹ��Ԥ�����ɵĻ���ӳ�����ͼ����л���У��
        ho_Image.Dispose();
        HOperatorSet.MapImage(ho_Image1, ho_Map, out ho_Image);
        //��У����Ĳ�ɫͼ��ת��Ϊ�Ҷ�ͼ��
        ho_GrayImage.Dispose();
        HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
        //====================== Mark���� ======================
        //�ڻҶ�ͼ��Ѱ�ҵ�һ��Mark�����״ģ��
        //����������ͼ��ģ��ID����ʼ�Ƕȡ��Ƕȷ�Χ����С�÷֡����ƥ�������ص��ȡ������ؾ��ȡ�������������̰���ȡ�����С��С��Ƕȡ��÷�
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_Mark1Row.Dispose();hv_Mark1Col.Dispose();hv_Mark1Angle.Dispose();hv_Score1.Dispose();
        HOperatorSet.FindShapeModel(ho_GrayImage, hv_ModelID1, (new HTuple(0)).TupleRad()
            , (new HTuple(360)).TupleRad(), 0.6, 1, 1, "least_squares", 0, 0.9, out hv_Mark1Row, 
            out hv_Mark1Col, out hv_Mark1Angle, out hv_Score1);
        }
        //�ڻҶ�ͼ��Ѱ�ҵڶ���Mark�����״ģ��
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_Mark2Row.Dispose();hv_Mark2Col.Dispose();hv_Mark2Angle.Dispose();hv_Score2.Dispose();
        HOperatorSet.FindShapeModel(ho_GrayImage, hv_ModelID2, (new HTuple(0)).TupleRad()
            , (new HTuple(360)).TupleRad(), 0.6, 1, 1, "least_squares", 0, 0.9, out hv_Mark2Row, 
            out hv_Mark2Col, out hv_Mark2Angle, out hv_Score2);
        }
        //���û�ͼ��ɫΪ��ɫ
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetColor(HDevWindowStack.GetActive(), "cyan");
        }
        //��ʾ��һ��Mark����������꣬����1λС��
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), (((new HTuple("Mark1 (Row,Col): (")+(hv_Mark1Row.TupleString(
              ".1f")))+new HTuple(", "))+(hv_Mark1Col.TupleString(".1f")))+")", "window", 
              10, 10, "cyan", new HTuple(), new HTuple());
          }
        }
        //��ʾ�ڶ���Mark����������꣬����1λС��
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), (((new HTuple("Mark2 (Row,Col): (")+(hv_Mark2Row.TupleString(
              ".1f")))+new HTuple(", "))+(hv_Mark2Col.TupleString(".1f")))+")", "window", 
              28, 10, "cyan", new HTuple(), new HTuple());
          }
        }
        //�ݴ��������������һ��Mark���ƥ��÷ֵ���0.6����Ϊδ�ҵ�
        if ((int)((new HTuple(hv_Score1.TupleLess(0.6))).TupleOr(new HTuple(hv_Score2.TupleLess(
            0.6)))) != 0)
        {
          //��ʾ��ǰ�Ҷ�ͼ��
          if (HDevWindowStack.IsOpen())
          {
            HOperatorSet.DispObj(ho_GrayImage, HDevWindowStack.GetActive());
          }
          //��ʾ��ɫ��Mark��δ�ҵ���ʾ��Ϣ������ɫ������
          if (HDevWindowStack.IsOpen())
          {
            HOperatorSet.DispText(HDevWindowStack.GetActive(), "Mark��δȫ���ҵ�", 
                "window", 46, 10, "red", "box", "true");
          }
          //��������ѭ��ʣ�ಿ�֣�������һ�βɼ�
          continue;
        }
        //====================== ����ת�����ƫ���� ======================
        //����һ��Mark��ĵ�ǰ��������ת��Ϊ��������
        hv_CurMark1X.Dispose();hv_CurMark1Y.Dispose();
        HOperatorSet.AffineTransPoint2d(hv_HomMat2D, hv_Mark1Col, hv_Mark1Row, out hv_CurMark1X, 
            out hv_CurMark1Y);
        //���ڶ���Mark��ĵ�ǰ��������ת��Ϊ��������
        hv_CurMark2X.Dispose();hv_CurMark2Y.Dispose();
        HOperatorSet.AffineTransPoint2d(hv_HomMat2D, hv_Mark2Col, hv_Mark2Row, out hv_CurMark2X, 
            out hv_CurMark2Y);
        //���㵱ǰ��Ʒ�����ĵ�X���꣺����Mark��X�����ƽ��ֵ
        hv_CurCenterX.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_CurCenterX = (hv_CurMark1X+hv_CurMark2X)/2.0;
        }
        //���㵱ǰ��Ʒ�����ĵ�Y���꣺����Mark��Y�����ƽ��ֵ
        hv_CurCenterY.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_CurCenterY = (hv_CurMark1Y+hv_CurMark2Y)/2.0;
        }
        //���㵱ǰ��Ʒ�ĽǶȣ�����Mark��������X��������ļн�(����)
        hv_CurAngle.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_CurAngle = ((hv_CurMark2Y-hv_CurMark1Y)).TupleAtan2(
            hv_CurMark2X-hv_CurMark1X);
        }
        //����X���ƫ������ǰ���ĵ�X - ��׼���ĵ�X
        //���壺��Ʒ����ڱ�׼λ����X���ƫ��������е��Ҫ�����ƶ��˾���
        hv_DeltaX.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_DeltaX = hv_CurCenterX-hv_StdCenterX;
        }
        //����Y���ƫ������ǰ���ĵ�Y - ��׼���ĵ�Y
        hv_DeltaY.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_DeltaY = hv_CurCenterY-hv_StdCenterY;
        }
        //����ǶȾ�ƫ������ǰ�Ƕ� - ��׼�Ƕ�(����)
        hv_DeltaAngle.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        hv_DeltaAngle = hv_CurAngle-hv_StdAngle;
        }
        //====================== �����ʾ ======================
        //��ʾ��ǰ�Ҷ�ͼ��
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.DispObj(ho_GrayImage, HDevWindowStack.GetActive());
        }
        //���û�ͼ��ɫΪ��ɫ
        //��ʾ��ǰMark��������
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetColor(HDevWindowStack.GetActive(), "cyan");
        }
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), ((("Mark1 (��������): ("+(hv_Mark1Row.TupleString(
              ".1f")))+new HTuple(", "))+(hv_Mark1Col.TupleString(".1f")))+")", "window", 
              10, 10, "cyan", new HTuple(), new HTuple());
          }
        }
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), ((("Mark2 (��������): ("+(hv_Mark2Row.TupleString(
              ".1f")))+new HTuple(", "))+(hv_Mark2Col.TupleString(".1f")))+")", "window", 
              30, 10, "cyan", new HTuple(), new HTuple());
          }
        }
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), ((("Mark1 ��������: ("+(hv_CurMark1X.TupleString(
              ".3f")))+new HTuple(", "))+(hv_CurMark1Y.TupleString(".3f")))+") mm", 
              "window", 50, 10, "cyan", new HTuple(), new HTuple());
          }
        }
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), ((("Mark2 ��������: ("+(hv_CurMark2X.TupleString(
              ".3f")))+new HTuple(", "))+(hv_CurMark2Y.TupleString(".3f")))+") mm", 
              "window", 70, 10, "cyan", new HTuple(), new HTuple());
          }
        }
        //��ʾ��ƫ��������Ҫ�ƶ���ֵ��
        if (HDevWindowStack.IsOpen())
        {
          HOperatorSet.SetColor(HDevWindowStack.GetActive(), "yellow");
        }
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), ("��X: "+(hv_DeltaX.TupleString(
              ".3f")))+" mm", "window", 90, 10, "yellow", new HTuple(), new HTuple());
          }
        }
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), ("��Y: "+(hv_DeltaY.TupleString(
              ".3f")))+" mm", "window", 110, 10, "yellow", new HTuple(), new HTuple());
          }
        }
        if (HDevWindowStack.IsOpen())
        {
          using (HDevDisposeHelper dh = new HDevDisposeHelper())
          {
          HOperatorSet.DispText(HDevWindowStack.GetActive(), ("����: "+(((hv_DeltaAngle.TupleDeg()
              )).TupleString(".2f")))+"��", "window", 130, 10, "yellow", new HTuple(), 
              new HTuple());
          }
        }
        // stop(...); only in hdevelop
      }
      //�ر�������ͷ���Դ
      HOperatorSet.CloseFramegrabber(hv_AcqHandle);
    }
    catch (HalconException HDevExpDefaultException)
    {
      ho_Image.Dispose();
      ho_Map.Dispose();
      ho_GrayImage.Dispose();
      ho_Mark1Rect.Dispose();
      ho_ImageReducedMark1.Dispose();
      ho_Mark2Rect.Dispose();
      ho_ImageReducedMark2.Dispose();
      ho_Image1.Dispose();

      hv_AcqHandle.Dispose();
      hv_Width.Dispose();
      hv_Height.Dispose();
      hv_WindowHandle.Dispose();
      hv_CameraParameters.Dispose();
      hv_CameraPose.Dispose();
      hv_row.Dispose();
      hv_column.Dispose();
      hv_rowworld.Dispose();
      hv_colmunworld.Dispose();
      hv_HomMat2D.Dispose();
      hv_ErrorSum.Dispose();
      hv_i.Dispose();
      hv_CalcX.Dispose();
      hv_CalcY.Dispose();
      hv_DiffX.Dispose();
      hv_DiffY.Dispose();
      hv_Error.Dispose();
      hv_AverageError.Dispose();
      hv__.Dispose();
      hv_Button.Dispose();
      hv_load_from_file.Dispose();
      hv_ModelID1.Dispose();
      hv_ModelID2.Dispose();
      hv_Params.Dispose();
      hv_RefMark1Row.Dispose();
      hv_RefMark1Col.Dispose();
      hv_RefMark2Row.Dispose();
      hv_RefMark2Col.Dispose();
      hv_StdMark1X.Dispose();
      hv_StdMark1Y.Dispose();
      hv_StdMark2X.Dispose();
      hv_StdMark2Y.Dispose();
      hv_StdCenterX.Dispose();
      hv_StdCenterY.Dispose();
      hv_StdAngle.Dispose();
      hv_Exception.Dispose();
      hv_Row11.Dispose();
      hv_Column11.Dispose();
      hv_Row12.Dispose();
      hv_Column12.Dispose();
      hv_Row21.Dispose();
      hv_Column21.Dispose();
      hv_Row22.Dispose();
      hv_Column22.Dispose();
      hv_Mark1Row.Dispose();
      hv_Mark1Col.Dispose();
      hv_Mark1Angle.Dispose();
      hv_Score1.Dispose();
      hv_Mark2Row.Dispose();
      hv_Mark2Col.Dispose();
      hv_Mark2Angle.Dispose();
      hv_Score2.Dispose();
      hv_CurMark1X.Dispose();
      hv_CurMark1Y.Dispose();
      hv_CurMark2X.Dispose();
      hv_CurMark2Y.Dispose();
      hv_CurCenterX.Dispose();
      hv_CurCenterY.Dispose();
      hv_CurAngle.Dispose();
      hv_DeltaX.Dispose();
      hv_DeltaY.Dispose();
      hv_DeltaAngle.Dispose();
      hv___Tmp_Ctrl_0_1.Dispose();

      throw HDevExpDefaultException;
    }
    ho_Image.Dispose();
    ho_Map.Dispose();
    ho_GrayImage.Dispose();
    ho_Mark1Rect.Dispose();
    ho_ImageReducedMark1.Dispose();
    ho_Mark2Rect.Dispose();
    ho_ImageReducedMark2.Dispose();
    ho_Image1.Dispose();

    hv_AcqHandle.Dispose();
    hv_Width.Dispose();
    hv_Height.Dispose();
    hv_WindowHandle.Dispose();
    hv_CameraParameters.Dispose();
    hv_CameraPose.Dispose();
    hv_row.Dispose();
    hv_column.Dispose();
    hv_rowworld.Dispose();
    hv_colmunworld.Dispose();
    hv_HomMat2D.Dispose();
    hv_ErrorSum.Dispose();
    hv_i.Dispose();
    hv_CalcX.Dispose();
    hv_CalcY.Dispose();
    hv_DiffX.Dispose();
    hv_DiffY.Dispose();
    hv_Error.Dispose();
    hv_AverageError.Dispose();
    hv__.Dispose();
    hv_Button.Dispose();
    hv_load_from_file.Dispose();
    hv_ModelID1.Dispose();
    hv_ModelID2.Dispose();
    hv_Params.Dispose();
    hv_RefMark1Row.Dispose();
    hv_RefMark1Col.Dispose();
    hv_RefMark2Row.Dispose();
    hv_RefMark2Col.Dispose();
    hv_StdMark1X.Dispose();
    hv_StdMark1Y.Dispose();
    hv_StdMark2X.Dispose();
    hv_StdMark2Y.Dispose();
    hv_StdCenterX.Dispose();
    hv_StdCenterY.Dispose();
    hv_StdAngle.Dispose();
    hv_Exception.Dispose();
    hv_Row11.Dispose();
    hv_Column11.Dispose();
    hv_Row12.Dispose();
    hv_Column12.Dispose();
    hv_Row21.Dispose();
    hv_Column21.Dispose();
    hv_Row22.Dispose();
    hv_Column22.Dispose();
    hv_Mark1Row.Dispose();
    hv_Mark1Col.Dispose();
    hv_Mark1Angle.Dispose();
    hv_Score1.Dispose();
    hv_Mark2Row.Dispose();
    hv_Mark2Col.Dispose();
    hv_Mark2Angle.Dispose();
    hv_Score2.Dispose();
    hv_CurMark1X.Dispose();
    hv_CurMark1Y.Dispose();
    hv_CurMark2X.Dispose();
    hv_CurMark2Y.Dispose();
    hv_CurCenterX.Dispose();
    hv_CurCenterY.Dispose();
    hv_CurAngle.Dispose();
    hv_DeltaX.Dispose();
    hv_DeltaY.Dispose();
    hv_DeltaAngle.Dispose();
    hv___Tmp_Ctrl_0_1.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void HDevelopExportMain(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

